### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by mbrookes** [mrphu3074/react-material-ui#13]
Hi Phu,

According to Atmosphere, the current version of this package is 0.1.6 as of Sep 8th, but looking at this repo, the current version is 0.1.5 as of Aug 23rd, and uses MUI 0.10.4.

Any idea what's going on? 

Thanks!
Matt.

**Comment by mrphu3074** [comment]
@mbrookes my mistake. I forgot commit new code to github. Only publish to Atmosphere.

**Comment by mbrookes** [comment]
Ah, I see. That makes sense. So what version of MUI is 0.1.6 using?

Also, the readme says "This package ported from Material-UI (a React Component) using the official Meteor React package." but also says "The code is also not updated to use the official react package yet. A new version will follow soon.". Which is it? :smile:

**Comment by mrphu3074** [comment]
i pushed new code. i using MUI 0.11.0 . You should use new version. They fixed alot of stuff
https://github.com/callemall/material-ui/blob/master/CHANGELOG.md#0110

**Comment by mbrookes** [comment]
Great, although the bottom of README still says "Note: This is an old demo with bugs and performance problems. The code is also not updated to use the official react package yet. A new version will follow soon."

Anyway, answers my question, so closing. Thanks for maintaining this!
