### ISSUE TITLE
Error after meteor update 1.2.0.2 and update MUI package to 0.1.7

### ISSUE THREAD

**Issue by vraptor75011** [mrphu3074/react-material-ui#16]
Seems there is a problem with updating cosmos:browserify to 0.7, i get this message at startup 

 While processing files with cosmos:browserify (for target web.browser):
   packages/izzilab:material-ui/mui.browserify.js: Arguments to path.resolve must be strings

Any idea ?

**Comment by mrphu3074** [comment]
i can't re-procedure your error. Can you share your log?

**Comment by vraptor75011** [comment]
Meteor update solved the issue.
Thks
