### ISSUE TITLE
browserify issue

### ISSUE THREAD

**Issue by johannchen** [mrphu3074/react-material-ui#17]
Hi,  I got this error prevented meteor startup
"While processing files with cosmos:browserify (for target os.linux.x86_64):
   packages/izzilab:material-ui/mui.browserify.js: Arguments to path.resolve
   must be strings"

It has no problem before I ran the meteor update to 1.2.0.2. 
cosmos:browserify is at version 0.7.4

**Comment by mrphu3074** [comment]
@johannchen , this is my mistake, cosmos:browserify >= 7.0 is for meteor >= 1.2. And cosmos:browserify 0.7 using isobuild 2 (new build tool of meteor 1.2) , so your meteor app will get that error. I need to create 2 versions:
- One ver support meteor < 1.2
- One else for >= 1.2

**Comment by johannchen** [comment]
Thanks for your quick response!  Hope to see one for >= 1.2 ready soon =)

**Comment by mrphu3074** [comment]
@johannchen i'm sorry my english not good and you may wrong understand. But just ask, did you update material-ui to latest version (0.1.7), if not, please run `meteor update izzilab:material-ui` or `meteor update izzilab:material-ui@0.1.7`

**Comment by johannchen** [comment]
Yes, it's at the latest version (0.1.7).  The error remains the same.

**Comment by vraptor75011** [comment]
Copying the package to your app/packages solves this issue. I don't know why ...

**Comment by johannchen** [comment]
The issue is also solved after I update cosmos:browserify to version 0.8

**Comment by mrphu3074** [comment]
thanks @johannchen , they fixed that bug in version 0.8

`Note: For Meteor 1.2 you must use comsos:browserify 0.8.0+`

many thanks, i will update my package
