### ISSUE TITLE
Datepicker works slowly

### ISSUE THREAD

**Issue by kysonic** [mrphu3074/react-material-ui#18]
When i  updated this package to 0.1.8 version MUI DatePicker stopped to work fine. Now it works slowly with many lags. (I use Chrome 45.0.2454.101 m, i've tested it in FF - everything is working normaly)

**Comment by mrphu3074** [comment]
@kysonic can you share your solution or how you solve it?

**Comment by kysonic** [comment]
@mrphu3074 Sorry, it was my fault, never mind...
