### ISSUE TITLE
support for core react

### ISSUE THREAD

**Issue by KristerV** [mrphu3074/react-material-ui#2]
Hey there. Really want to use Material-UI with the official react package (`meteor add react`), but just can't figure out how to manipulate this package in order for it to work. Let alone making my own package :)

Can you please convert this package or direct me in the right way?

**Comment by mrphu3074** [comment]
Yes, i can. `meteor add react` is really new (i think) :)
Let's me create new branch.

Thanks @KristerV

**Comment by mrphu3074** [comment]
@KristerV  but there is an issue. We have 2 React instance tyoe in app.
One from mui components use npm React
One from `meteor add react`
So we cannot assign context from parent to childrens(mui components)
ex:

``` javascript
// react from meteor add react
App = React.createClass({
        mixins: [ReactMeteorData],
        getMeteorData: function() {
            return {};
        },
        themeManager: new MUI.Styles.ThemeManager(),
        // IMPORTANT. SET CHILD CONTEXT
        childContextTypes: {
            muiTheme: React.PropTypes.object,
        },
        getChildContext: function() {

          return {
              muiTheme: this.themeManager
          }
        },
```

``` javascript
let React = require('react'); // react from npm package
let StylePropable = require('./mixins/style-propable');
let Typography = require('./styles/typography');
let IconButton = require('./icon-button');
let NavigationMenu = require('./svg-icons/navigation/menu');
let Paper = require('./paper');


let AppBar = React.createClass({

  mixins: [StylePropable],

  contextTypes: {
    muiTheme: React.PropTypes.object,
  },
```

do you know how to solve it???

**Comment by KristerV** [comment]
I'm working on it in [my own repo](https://github.com/KristerV/meteor-material-ui) and discussing this [on the forum](https://forums.meteor.com/t/material-ui-with-react-js). Really want to get this fixed somehow :)

Maybe you can have a look. My repo has a demo app built in, just run meteor in the `demo` folder.

Currently the issue is, that "require" is not defined - even though I'm using browserify exactly like you are here..

**Comment by KristerV** [comment]
oh, actually. I think maybe the solution to your current problem is using transforms with browserify? https://github.com/meteor/react-packages/blob/master/examples/material-ui-leaderboard/client/lib/app.browserify.options.json

**Comment by mrphu3074** [comment]
Oh man, thankyou so much. I will try

**Comment by mrphu3074** [comment]
@KristerV  thanks for your solution.
I updated my package and it supported `meteor add react`

**Comment by mrphu3074** [comment]
But in this time, i export namespaces: mui, MUI and injectTapEventPlugin
It means: 
- You have to use injectTapEventPlugin() manually
- mui and MUI are the same.

**Comment by KristerV** [comment]
wow, you've done it already? let me try that out..

**Comment by KristerV** [comment]
holy shit it works.. you are amazing :O

**Comment by KristerV** [comment]
yep. tested is some more. Thanks!

**Comment by stubailo** [comment]
For people who come along later, here is the page in the guide about this: http://react-in-meteor.readthedocs.org/en/latest/client-npm/

There are some crazy hacks to avoid React duplication :P

**Comment by KristerV** [comment]
boy, @stubailo you are thorough :) looking forward to the crowdcast. ([link](https://www.crowdcast.io/e/aliceyu1) if anyone is interested)
