### ISSUE TITLE
Datepicker not rendering properly

### ISSUE THREAD

**Issue by Timonzimm** [mrphu3074/react-material-ui#20]
When trying to use the DatePicker component the example in the README, it looks like it's not rendering properly.

![Test](https://cloud.githubusercontent.com/assets/5808319/10514474/2b8b1f9a-734e-11e5-9c3b-5b030d563bea.png)

**Comment by mrphu3074** [comment]
@Timonzimm i have never seen it, if DatePicker error, it can't render . Can you share some code ?

**Comment by Timonzimm** [comment]
I think this might be due to ReactLayout package (https://github.com/kadirahq/meteor-react-layout) which creates a new body tag when the DatePicker in instancid.
