### ISSUE TITLE
ThemeManager.getMuiTheme is not a function. 

### ISSUE THREAD

**Issue by dcjohnston** [mrphu3074/react-material-ui#21]
In the getting started we have this snippet. 

``` javascript
  getChildContext() {
    return {
      muiTheme: ThemeManager.getMuiTheme(LightRawTheme)
    };
  },
```

I have replicated exactly but am getting the error above. Is this no longer valid?

**Comment by jhuenges** [comment]
I copied the package and removed the version restriction of react and updated to the latest material ui version.

**Comment by dcjohnston** [comment]
Great! I think the recent Meteor update to 1.2 has had a lot of package maintainer's hustling to update as well, thanks for being so responsive!

**Comment by mrphu3074** [comment]
@dcjohnston alot of issues relate to meteor, especially installing npm module, it's so bad. thanks for your issue
