### ISSUE TITLE
Can you please update it to material-Ui 0.13?

### ISSUE THREAD

**Issue by tapas4java** [mrphu3074/react-material-ui#22]
Pls update

**Comment by mrphu3074** [comment]
hi @tapas4java,

MUI 0.13.0 using react 0.14 but Meteor react package does not upgrade. Facebook separated react to 2 things: react and react-dom, so i can't upgrade mui for now.

sorry about that.

**Comment by coniel** [comment]
The meteor react package has been updated to 0.14. Could we update to 0.13 now?
