### ISSUE TITLE
ThemeManager.getMuiTheme is not a function

### ISSUE THREAD

**Issue by tapas4java** [mrphu3074/react-material-ui#23]
Getting below error when trying to run example code given:

`ThemeManager.getMuiTheme is not a function`

**Comment by mrphu3074** [comment]
@tapas4java sorry about my question: did you import ThemeManager from MUI.Styles?
like below

```
var {
    AppCanvas,
    AppBar,
    Styles
    } = MUI;
var { ThemeManager, LightRawTheme } = Styles;

```

**Comment by tapas4java** [comment]
Yes @mrphu3074 I am using the same code available on README doc with latest Meteor. Here is the code for your reference

```
var {
    AppCanvas,
    AppBar,
    Styles,
    RaisedButton,
    DatePicker
    } = MUI;
var { ThemeManager, LightRawTheme } = Styles;

App = React.createClass({
    childContextTypes: {
        muiTheme: React.PropTypes.object
    },

    getChildContext() {
        return {
            muiTheme: ThemeManager.getMuiTheme(LightRawTheme)
        };
    },
```

**Comment by dcsan** [comment]
I got the same error. we fixed it with:

```
  getChildContext() {
    return {
      muiTheme: ThemeManager(LightRawTheme)
    };
  },

```

any idea why the README is wrong?

**Comment by mrphu3074** [comment]
@dcsan i'm not sure about your way, but this is official example,
https://github.com/callemall/material-ui/blob/master/examples/browserify-gulp-example/src/app/components/main.jsx

**Comment by jordangarside** [comment]
After looking at this,

ThemeManager.getMuiTheme(theme) is an undefined function.
Using ThemeManager(theme) just returns the default theme, while ignoring whatever theme you have specified.
LightRawTheme is actually undefined and doesn't exist on the Styles object.

Hoping for a solution, I can't theme anything right now.

**Comment by mrphu3074** [comment]
@jordangarside can you share your code or create a test project and write some components that can't use ThemeManager

**Comment by jordangarside** [comment]
Here is the [demo](https://github.com/Tesloop/marketing-site).

You can see the ThemeManger stuff [here](https://github.com/Tesloop/marketing-site/blob/master/components/layouts/DefaultLayout/DefaultLayout.import.jsx) line 87.
The theme I'd like to use is imported at the top of the file, but just does what I mentioned before.

If you look at the window variable, MUI.Styles.ThemeManager.getMuiTheme is undefined, as well as MUI.Styles.LightRawTheme. If you try to import the LightRawTheme and console.log it, it will be undefined.

**Comment by mrphu3074** [comment]
sorry but you're using old MUI version

```
id-map@1.0.4
insecure@1.0.4
izzilab:material-ui@0.1.6
jquery@1.11.4
jsx@0.2.3
kadira:flow-router@2.9.0
kadira:react-layout@1.4.1
launch-screen@1.0.4
```

You need to upgrade to latest version (0.2.2) to use MUI 0.13.3
