### ISSUE TITLE
How to add icons?

### ISSUE THREAD

**Issue by pgorecki** [mrphu3074/react-material-ui#24]
I'm trying to add NavigationClose icon to a toolbar. Here is the code. How can I import NavigationClose component?

```
var {
    AppCanvas,
    AppBar,
    IconButton,
    FlatButton,
    NavigationClose,
    Styles,
    } = MUI;
var { ThemeManager, LightRawTheme, DarkRawTheme } = Styles;


var App = React.createClass({
    childContextTypes: {
        muiTheme: React.PropTypes.object
    },

    getChildContext() {
        return {
            muiTheme: ThemeManager.getMuiTheme(LightRawTheme)
        };
    },

    render: function () {
        return (
            <AppCanvas>
                <AppBar
                  title="Title"
                  iconElementLeft={<IconButton><NavigationClose /></IconButton>}
                  iconElementRight={<FlatButton label="Save" />} />
            </AppCanvas>
        );
    }
});

if (Meteor.isClient) {
    Meteor.startup(() => React.render(<App/>, document.body));
}
```

**Comment by mrphu3074** [comment]
in Meteor, we define component without `var` or `let`, your component will be global and no need to import.

**Comment by pgorecki** [comment]
Maybe I didn't make myself clear enough. Your package dependes on Npm material-ui package from https://github.com/callemall/material-ui repository. In this repo `NavigationClose` component is defined in the file `material-ui/src/svg-icons/navigation/close.jsx`. Is there any way I can import this component to my project?  I'm simply trying to display the second AppBar example from http://material-ui.com/#/components/appbar using Meteor and your package.

**Comment by mrphu3074** [comment]
thanks @pgorecki about your issue. This is my mistake because i thought we can use FontIcon with external icon libs like Font-Awesome or Material font like this `dapearce:material-icons`. So i didn't import svg-icons. 

In new version 0.2.0, i upgraded MUI 0.13.1 , react and react-dom to 0.14.1 and imported SvgIcons.
You can use `MUI.Libs.SvgIcons.[ICON component]`

```
    let {SvgIcons} = MUI.Libs;
    ...
    render() {
            let RightIcon = <SvgIcons.NavigationClose />
            return (
                <AppCanvas>
                    <AppBar title="izziLab" iconElementRight={RightIcon} />
                </AppCanvas>
            );
        }
```

 thank you

**Comment by rdagger** [comment]
I'm also unable to figure out how to add an icon to the AppBar iconElementRight.  I updated izzilab:material-ui to 0.1.9.  Do I have to wait for version .2.0?
In the current version, MUI.Libs does have SvgIcons.

**Comment by mrphu3074** [comment]
my package was 0.2.1 already, please update and feedback to me if any error

**Comment by rdagger** [comment]
works great now.  thanks.

**Comment by mrphu3074** [comment]
good sound, thanks @rdagger

**Comment by HenrikBechmann** [comment]
Hi, I installed 0.2 but it seemed to be from 2014. I upgraded to 0.13.4 which seems to be the most recent.

I still can't init NavigationClose successfully.

(Using Typescript)

Thanks.
