### ISSUE TITLE
 Warning: require('react/addons') is deprecated.

### ISSUE THREAD

**Issue by Boityakov** [mrphu3074/react-material-ui#25]
Hello, console display me a:
"Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead."

My meteor list
angular                               1.0.3  Everything you need to use Angul...
angular:angular-material              0.11.4  Google Material design written ...
angularui:angular-ui-router           0.2.15  angular-ui-router (official): F...
blaze-html-templates                  1.0.1  Compile HTML templates into reac...
izzilab:material-ui                   0.1.8  Material-UI using official React...
jquery                                1.11.4  Manipulate the DOM using CSS se...
meteor-base                           1.0.1  Packages that every Meteor app n...
mquandalle:bower                      1.5.2_1  Use Bower packages in your Met...
react                                 0.14.1_1  Everything you need to use Re...

**Comment by mrphu3074** [comment]
@Maiti react didn't upgrade to 0.14.x when i upgrade my package. Now `izzilab:material-ui@0.1.9` using react and react-dom 0.14.x and mui to 0.13.1

Please upgrade and check it again. Looking forward your reply soon.

**Comment by Boityakov** [comment]
Warning still exists

meteor list
angular                               1.0.3  Everything you need to use Angul...
angular:angular-material              0.11.4  Google Material design written ...
angularui:angular-ui-router           0.2.15  angular-ui-router (official): F...
blaze-html-templates                  1.0.1  Compile HTML templates into reac...
izzilab:material-ui                   0.1.9  Material-UI using official React...
jquery                                1.11.4  Manipulate the DOM using CSS se...
meteor-base                           1.0.1  Packages that every Meteor app n...
mquandalle:bower                      1.5.2_1  Use Bower packages in your Met...
react                                 0.14.1_1  Everything you need to use Re...

**Comment by mrphu3074** [comment]
@Maiti can you give me how you can get that warning ? what components that you used ?

Because i'm not use react/addons and in module material ui only use in 2 places and they are in test files.

**Comment by Boityakov** [comment]
I comment one by one packages, and remove all mui components, but nothing helped, warning is always displayed

**Comment by Boityakov** [comment]
and when I click on the "... Dialog"s console displayed me
"Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `Dialog`."

**Comment by mrphu3074** [comment]
please update to latest version. i think it will solve your issue.
