### ISSUE TITLE
Use with SSR

### ISSUE THREAD

**Issue by jimmiebtlr** [mrphu3074/react-material-ui#27]
At the moment it doesn't appear to be exposed on the server, making it difficult to use with flow router ssr.

Can we get MUI exposed on the server?

**Comment by mrphu3074** [comment]
@jimmiebtlr i just upgraded MUI to 0.2.0 without SSR, i having trouble with `meteor` and `cosmos:browserify` since meteor 1.2.x released. I investigating the solution to support SSR

**Comment by mrphu3074** [comment]
@jimmiebtlr i just updated my package to 0.2.1 to fix SSR, please update and test your app. Looking forward your feedback soon.

**Comment by gh-stephane-barale** [comment]
Hi @mrphu3074,
AppBar is broken with SSR due to docked option (use Overlay component) and it seems fix in 1.3.2.
https://github.com/callemall/material-ui/issues/2013

Can you upgrade MUI version please ?

**Comment by mrphu3074** [comment]
@C0r3y8  i will , it's simple. Just busy somedays.

**Comment by gh-stephane-barale** [comment]
Ok thanks, no problem.

**Comment by mrphu3074** [comment]
@C0r3y8 done, now MUI is 0.13.3

**Comment by gh-stephane-barale** [comment]
Thanks! @mrphu3074

**Comment by gh-stephane-barale** [comment]
Works fine after clearing Meteor app cache
