### ISSUE TITLE
Getting latest version of Material UI

### ISSUE THREAD

**Issue by rdagger** [mrphu3074/react-material-ui#28]
If I want to use the latest version of Material UI before you upgrade your package, can I just change MUI_VERSION in the packages.js file?  For example change var MUI_VERSION = '0.13.1'; to var MUI_VERSION = '0.13.2';

**Comment by mrphu3074** [comment]
Basically, yes :+1:

**Comment by mrphu3074** [comment]
i also upgraded my package to 0.13.3. If you want to manual control, it's totally ok.
