### ISSUE TITLE
SwipeableViews

### ISSUE THREAD

**Issue by flake** [mrphu3074/react-material-ui#29]
I am using Tabs with slide effect. But how do I import SwipeableViews??

SwipeableViews = require('react-swipeable-views');

Thank you

**Comment by mrphu3074** [comment]
This is a normal npm module, you can import to meteor with  package `cosmos:browserify`
Let's try
https://atmospherejs.com/cosmos/browserify

**Comment by flake** [comment]
Thank you. I did import it using cosmos:browserify.

I am guessing the package is included with material-ui as well...
