### ISSUE TITLE
Using SSR with Material UI (Headers)

### ISSUE THREAD

**Issue by sergical** [mrphu3074/react-material-ui#31]
I get the following error `Material-UI expects the global navigator.userAgent to be defined for server-side rendering. Set this property when receiving the request headers.`

Unable to find any docs in the package regarding this issue.

**Comment by mrphu3074** [comment]
@416serg i have no idea for now. But there are the  same issues from official : https://github.com/callemall/material-ui/issues/2356

Hope to finding solution soon

**Comment by markshust** [comment]
This can probably be closed, readme at:
http://www.material-ui.com/#/get-started/server-rendering

setting userAgent to false if no prefixes needed, or safari line if needed, fixes this

**Comment by mrphu3074** [comment]
thanks. but this package dedicated. we use npm module for now
