### ISSUE TITLE
Q: How to use mixins with react-material-ui and meteor?

### ISSUE THREAD

**Issue by nikos** [mrphu3074/react-material-ui#32]
In the process of adapting a react component (https://github.com/nikos/material-ui-bottomnav/blob/master/src/app/components/bottom-nav.js) to the "meteor" style, I am uncertain how to deal with mixins (concrete: StylePropable, WindowListenable)

```
var {
    Overlay,
    Paper,
    Menu,
    Styles
    } = MUI;

import StylePropable from 'material-ui/mixins/style-propable'; // ???
var { ThemeManager, LightRawTheme, Transitions } = Styles;
```

Could you please advise?

Many Thanks in advance,
Niko

**Comment by mrphu3074** [comment]
in Meteor and with my package, you can use mixin via `MUI.Mixins`

``` jsx

var {
    Overlay,
    Paper,
    Menu,
    Styles,
    Mixins
    } = MUI;

var { ThemeManager, LightRawTheme, Transitions } = Styles;
var { StylePropable, WindowListenable } = Mixins
```

**Comment by nikos** [comment]
Thanks for your help, works like a charm
