### ISSUE TITLE
update to latest from upstream?

### ISSUE THREAD

**Issue by dcsan** [mrphu3074/react-material-ui#33]
I have some problems with the current version, i was wondering what is involved to update to the latest?

did you make any changes to the upstream package itself?

https://github.com/callemall/material-ui/issues/2544#issuecomment-165049496

**Comment by dcsan** [comment]
I updated to 0.14.0-rc2 in my fork, seems to be working ok
its still a release candidate tho so you may want to hold off.

https://github.com/dcsan/react-material-ui/commit/0a8c3f259c1c13622ba079902f69780afde34156

**Comment by mrphu3074** [comment]
i didn't upgrade to latest version **0.14.0-rc2** because it still be release candidate ver. I think they almost done with 0.14.0-rc2 , you can use your fork first, thanks

**Comment by rdagger** [comment]
Looks like 0.14.0 was just released with many long awaited bug fixes.

**Comment by mrphu3074** [comment]
@rdagger i upgraded to MUI 0.14.0 and react 0.14.3 . Please update. thanks for your issue

**Comment by dcsan** [comment]
thanks!
