### ISSUE TITLE
how to use font icons

### ISSUE THREAD

**Issue by dcsan** [mrphu3074/react-material-ui#34]
I tried using font-icons as per the material-ui docs, but without success

http://www.material-ui.com/#/components/icons

```
<FontIcon className="muidocs-icon-action-home" />
<FontIcon className="material-icons">home</FontIcon>

```

no icon shows up.

do i need to use  `let {SvgIcons} = MUI.Libs;`  somehow?
that seems to define standalone svg icons, but not the classnames to apply an icon to a div.

**Comment by dcsan** [comment]
also for the badges
http://www.material-ui.com/#/components/badge

It seems the names in that list are not defined within the MUI package (I guess this is how they are packaged upstream in material-ui itself)

```
<Badge badgeContent={4} primary={true}>
  <NotificationsIcon />
</Badge>
```

![image](https://cloud.githubusercontent.com/assets/514002/11914648/0817d86c-a63b-11e5-9b64-4064557a6f11.png)

OK so this works

```
let NotifIcon = MUI.Libs.SvgIcons.NotificationDoNotDisturb;

// and in render( ) {
 <NotifIcon />
```

**Comment by mrphu3074** [comment]
@dcsan font icon in mui doc just sample, you need import font library to use it.
like Font-Awesome
`<FontIcon className="fa fa-star" />`

**Comment by dcsan** [comment]
so you're saying the material-ui docs refer to icons that are not packaged with that project?

but you are including one set of SVG icons in your package? 
I'm worried about the app getting huge if there are two big sets of font icons in it.

**Comment by mrphu3074** [comment]
There are 2 options:
- Use icons built in : use  `SvgIcons`
- Use icons external: use `FontIcon`

**Comment by Davy1992** [comment]
In material-ui **0.15.0** I can't get FontIcon to work, I followed the docs but when I do this:
`<MenuItem leftIcon={<FontIcon className="material-icons">settings</FontIcon>}>Settings</MenuItem>`

I don't get the icon but the text `settings` instead.

Please help!
