### ISSUE TITLE
Failed to validate checksum

### ISSUE THREAD

**Issue by priyankpat** [mrphu3074/react-material-ui#37]
Hi, I am using meteor with server-sided rendering. I just came across this package. Upon adding FlatButton or any component for that matter, I get the following error:

> React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server.

**Comment by mrphu3074** [comment]
@PR1YANKPAT3L  thanks for your issue, but i have no idea. The reason is we render 2 times in both sides, so they are quite difference about inline-styles like 

```
(client) d;z-index:1300;left:0;top:0;transform:tr
 (server) d;z-index:1300;left:-266px;top:0;transfo
```

because user agents are difference. I'm finding solution too
