### ISSUE TITLE
SelectableContainerEnhance is undefined

### ISSUE THREAD

**Issue by pmwisdom** [mrphu3074/react-material-ui#38]
As of 2.4 I cant access SelectableContainerEnhance. I believe it has something to do with the new version of browserify. 

Repro:

```
let { SelectableContainerEnhance, List } = MUI;
let SelectableList = SelectableContainerEnhance.SelectableContainerEnhance(List);

```

Error : SelectableContainerEnhance is undefined.

This worked perfectly before 2.4.

**Comment by guns2410** [comment]
+1 have the same issue

**Comment by gh-stephane-barale** [comment]
+1

**Comment by mrphu3074** [comment]
plz upgrade to latest version and try:

``` jsx
const {SelectableContainerEnhance, List} = MUI;
const SelectableList  = SelectableContainerEnhance(List)
```

**Comment by mrphu3074** [comment]
it seems they changed a little bit. :dancers:

**Comment by pmwisdom** [comment]
Yep that worked like a charm. Thanks!
