### ISSUE TITLE
How to use a custom Icon

### ISSUE THREAD

**Issue by cbrake** [mrphu3074/react-material-ui#39]
Hi,

Trying to figure out a way to use a custom icon in izzilab:material-ui.  I have the custom icon in a SVG file.  Does it need processed into a sprite before I can use it in:

```
<SvgIcon {...this.props}>
        <path d="?????"></path>
</SvgIcon>
```

If so, what is the best way to make this happen?  Or, can I simply put the SVG in the public dir, and reference it directly?

Thanks,
Cliff

**Comment by mrphu3074** [comment]
Please read this document if you use custom `SvgIcon`.
http://www.material-ui.com/#/components/svg-icon

```
const iconStyles = {
  marginRight: 24,
};

const HomeIcon = (props) => (
  <SvgIcon {...props}>
    <path d="M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8z" />
  </SvgIcon>
);

const SvgIconExampleSimple = () => (
  <div>
    <HomeIcon style={iconStyles} />
    <HomeIcon style={iconStyles} color={Colors.blue500} />
    <HomeIcon style={iconStyles} color={Colors.red500} hoverColor={Colors.greenA200} />
  </div>
);
```

**Comment by cbrake** [comment]
Thanks!

**Comment by oiricaud** [comment]
What if you are trying to use a custom svg? For example a non-material ui icon. What is the argument of the path? Is it the <path d="the path to the svg file?" />
