### ISSUE TITLE
Double installation of react in Meteor 1.3

### ISSUE THREAD

**Issue by rnarayan** [mrphu3074/react-material-ui#46]
I am using Meteor 1.3 and its suggested "imports" folder structure to import only the modules that are needed. I am using the npm install of react in the project. For material ui, I noticed that if I install izzilab:material-ui package, it installs another copy of react. Is there a way to avoid that? Thanks.

**Comment by mrphu3074** [comment]
my package deprecated in meteor 1.3. Please use MUI official `npm install material-ui`

**Comment by rnarayan** [comment]
Thanks.
