### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by coniel** [mrphu3074/react-material-ui#6]
I'm planning on using SSR (see here: https://kadira.io/blog/meteor-ssr-support-using-flow-router-and-react/).

However, this package the required stuff (react package, exports) are only for client side. Would it be possible to modify it so that things are also available on the server?

**Comment by stubailo** [comment]
Duplicate of #5

I think the time diff was like, 10 seconds?

**Comment by coniel** [comment]
Oh wow haha, I'll close this one then.
