### ISSUE TITLE
Production mode

### ISSUE THREAD

**Issue by Valbrand** [mrphu3074/react-material-ui#8]
Hello.

Whenever I add izzilab:material-ui to my project, I keep getting an error while in production mode (it doesn't manifest itself if I run the project in debug mode). It seems to look for window.React.require before React is put in the global context, as I get a "window.React is undefined" TypeError message in Firebug.

**Comment by mrphu3074** [comment]
@Valbrand is this solved? I trying to get your error.

**Comment by Valbrand** [comment]
I am not sure. I still can't get it to work in production mode, though I am not so sure if it's actually my fault or not.

**Comment by Valbrand** [comment]
Okay, here's the thing: I've just created a clean Meteor project, and inside of it, I created a local package which uses React. Fine, it works both in production and debug mode. However, if I add this package, the problem arises. It exists.

**Comment by mrphu3074** [comment]
oh, maybe conflicted between react runtime in mui package and your react runtime. Can you give me the react package name in your local packages?

**Comment by Valbrand** [comment]
This test project I created is structured as follows:
In the app itself, the only package besides meteor-platform that's installed is the local package, `test-ui`. Inside `test-ui`'s `package.js`, I call `api.use` for `templating`, `react`, and `izzilab:material-ui@0.1.0`, in this order.

**Comment by mrphu3074** [comment]
@Valbrand i found your problem. You're right! . This error cause by react package official hide `window.React` in production mode. So `externalify` throw error undefined. I solved and pushed new code in new branch. Please check it again manually.
1. create new project
2. cd /pathto/project
3. mkdir packages
4. cd packages
   `git clone -b missing-react-production https://github.com/mrphu3074/react-material-ui.git`
5. meteor --production and play it.

IF it work,  i will merge them and update smart package.

**Comment by Valbrand** [comment]
Just tested it, and it worked. Thank you, mate.

**Comment by mrphu3074** [comment]
@Valbrand i merged the code and update package on atmospherejs. You can close this issue. Thankyou so much .

**Comment by Valbrand** [comment]
Problem solved.
